### Consulta de producto
GET http://wwwproyectosexto/productos

### Modificar Productos
PUT http://wwwproyectosexto/productos/1

hearders:Content-Type: application/json
{
   "id_producto":1,
   "nombre":"Leche Entera 1L",
   "categoria":"Lacteos",
   "precio_copra":"0,84",
   "precio_venta":"1,20",
   "fecha_vencimiento":"2026-08-15",
   "estado":"Disponible"
}